
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("posts/new", "Create posts")) ?>
</div>

<?php echo $this->tag->form(array("posts/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search posts</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("title", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="body">Body</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("body", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="excerpt">Excerpt</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("excerpt", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="published">Published</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("published", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated">Updated</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="pinged">Pinged</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("pinged", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="to_ping">To Of Ping</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("to_ping", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
